name = "linkdump-bot-complete"
main = "complete-app.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# R2 Bucket 바인딩
[[r2_buckets]]
binding = "LINKDUMP_STORAGE"
bucket_name = "linkdump-data"

# Secrets (wrangler secret put으로 설정):
# wrangler secret put ANTHROPIC_API_KEY
# wrangler secret put DISCORD_WEBHOOKS