name = "linkdump-bot"
main = "app.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# R2 Bucket binding
[[r2_buckets]]
binding = "LINKDUMP_STORAGE"
bucket_name = "linkdump-data"

# Workers AI binding
[ai]
binding = "WORKERS_AI"

# Secrets (set with `wrangler secret put <name>`):
# wrangler secret put DISCORD_WEBHOOKS