name = "linkdump-bot-workers-ai"
main = "complete-app.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# R2 Bucket 바인딩
[[r2_buckets]]
binding = "LINKDUMP_STORAGE"
bucket_name = "linkdump-data"

# Workers AI 바인딩
[ai]
binding = "AI"

# Secrets (wrangler secret put으로 설정):
# wrangler secret put DISCORD_WEBHOOKS
# ANTHROPIC_API_KEY는 더 이상 필요 없음!